name: BERGERON
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.0.5
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - expat=2.6.2
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=73.1
  - idna=3.7
  - importlib_metadata=8.5.0
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libllvm10=10.0.1
  - libllvm14=14.0.6
  - libpng=1.6.39
  - libpq=12.17
  - libstdcxx-ng=11.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - llvmlite=0.41.0
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mysql=5.7.24
  - ncurses=6.4
  - numba=0.58.1
  - numexpr=2.8.4
  - numpy-base=1.24.3
  - openjpeg=2.4.0
  - openssl=3.0.15
  - pandas=1.4.2
  - pcre2=10.42
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - pynndescent=0.5.13
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.19
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2024.1
  - qt-main=5.15.2
  - readline=8.2
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - seaborn=0.13.2
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.3.3
  - umap-learn=0.5.6
  - unicodedata2=15.1.0
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - accelerate==0.30.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - certifi==2024.2.2
      - datasets==2.19.1
      - diffusers==0.27.2
      - dill==0.3.8
      - filelock==3.14.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - h5py==3.11.0
      - huggingface-hub==0.23.0
      - importlib-metadata==7.1.0
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.1.105
      - packaging==24.0
      - psutil==5.9.8
      - pyarrow==16.0.0
      - pyarrow-hotfix==0.6
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.1
      - regex==2024.4.28
      - requests==2.31.0
      - safetensors==0.4.3
      - sympy==1.12
      - tokenizers==0.19.1
      - torch==2.3.0
      - torchvision==0.18.0
      - tqdm==4.66.4
      - transformers==4.40.2
      - triton==2.3.0
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.18.1
